const LOESUNGEN_HAK3 = {
  marketing: [
      `<strong>Marketing-Mix (4 P's) für die AlpenBar:</strong><ul><li><strong>Produkt:</strong> Bio-Müsliriegel mit Tiroler Heumilchschokolade, regionale Zutaten, nachhaltige Verpackung, Zertifizierungen (AMA, Bio Austria)</li><li><strong>Preis:</strong> € 2,49 → Premiumpreis-Strategie (Bio-Qualität rechtfertigt höheren Preis als Standardriegel)</li><li><strong>Distribution (Place):</strong> Supermärkte (REWE, SPAR), Bio-Läden, eigener Onlineshop, Tankstellen/Kioske</li><li><strong>Kommunikation (Promotion):</strong> Social Media (Instagram, TikTok), regionale Influencer, Messen (BioFach), Verkostungsaktionen</li></ul>`,
      `<strong>Marktforschung:</strong> Systematische Sammlung und Auswertung von Informationen über Märkte, Kunden und Konkurrenten.<br><br><strong>Primärforschung</strong> (neue Daten erheben): z.B. AlpenFresh führt eine Online-Umfrage unter 200 Personen zur Zahlungsbereitschaft durch.<br><strong>Sekundärforschung</strong> (vorhandene Daten nutzen): z.B. AlpenFresh wertet Statistik Austria-Daten zum Bio-Lebensmittelkonsum aus oder nutzt Marktberichte von Branchenverbänden.`,
      `<strong>Budgetverteilung € 30.000:</strong><ul><li>Instagram/TikTok Ads: € 10.000 (33%) – erreicht Zielgruppe 25–45 direkt</li><li>Verkostungsaktionen in Supermärkten: € 8.000 (27%) – direkte Kaufentscheidung am POS</li><li>Influencer Marketing (Mikro-Influencer, regional): € 6.000 (20%) – authentisch, kostengünstig</li><li>Printmaterial (Aufsteller, Flyer): € 3.000 (10%) – für POS-Präsenz</li><li>PR / Pressearbeit: € 3.000 (10%) – Artikel in Regionalpresse, Bio-Magazinen</li></ul>`,
      `<strong>Break-even-Berechnung:</strong><br>Stückdeckungsbeitrag = VKP − variable Kosten = € 2,49 − € 0,85 = <strong>€ 1,64</strong><br>Break-even-Menge = Fixkosten ÷ Stückdeckungsbeitrag = € 30.000 ÷ € 1,64 = <strong>18.293 Stück</strong><br>→ AlpenFresh muss mindestens 18.293 AlpenBars verkaufen, bevor die Marketingkosten gedeckt sind und Gewinn entsteht.`
    ],
  preisgestaltung: [
      `<strong>Deckungsbeitragsrechnung:</strong><br>DB/Stück = VKP − variable Kosten = € 2,49 − € 0,85 = <strong>€ 1,64</strong><br>Gesamtdeckungsbeitrag = € 1,64 × 15.000 Stück = <strong>€ 24.600/Monat</strong><br>Fixkosten: € 12.000/Monat<br>Gewinn = € 24.600 − € 12.000 = <strong>€ 12.600/Monat</strong> ✓ → Ja, Gewinn ist möglich!`,
      `<strong>Cost-Plus-Pricing Berechnung:</strong><br>Variable Kosten/Stück: € 0,85<br>Fixkosten/Stück: € 12.000 ÷ 15.000 = € 0,80<br>Gesamtkosten/Stück: € 0,85 + € 0,80 = € 1,65<br>Aufschlag 40 %: € 1,65 × 1,40 = <strong>€ 2,31</strong><br>→ Kalkulierter Preis: ca. € 2,31. Da die Konkurrenz bis zu € 2,80 verlangt, ist € 2,49 als Premiumpreis gut positioniert.`,
      `<table><tr><th>Strategie</th><th>Vorteile</th><th>Nachteile</th></tr><tr><td><strong>Niedrigpreis</strong></td><td>Hohe Absatzmenge, schnelle Marktdurchdringung</td><td>Schadet dem Bio-Image, gefährdet Deckungsbeitrag</td></tr><tr><td><strong>Premiumpreis</strong></td><td>Passt zum Bio-Markenwert, höhere Margen</td><td>Geringere Absatzmenge, Kunden müssen überzeugt werden</td></tr><tr><td><strong>Konkurrenzorientiert</strong></td><td>Marktkonform, leicht verständlich</td><td>Reagiert nur, keine eigenständige Positionierung</td></tr></table><br>→ <strong>Empfehlung: Premiumpreis (€ 2,49)</strong> passt zum regionalen Bio-Image von AlpenFresh.`,
      `<strong>Break-even bei verschiedenen Preisen:</strong><br>Bei VKP € 2,49: DB = € 1,64 → Break-even = € 12.000 ÷ € 1,64 = <strong>7.317 Stück</strong><br>Bei VKP € 2,99: DB = € 2,14 → Break-even = € 12.000 ÷ € 2,14 = <strong>5.607 Stück</strong><br>→ Bei € 2,99 wird die Gewinnschwelle früher erreicht → <strong>geringeres Risiko</strong>. Aber: Höherer Preis kann die Absatzmenge senken – das muss abgewogen werden.`
    ],
  personal: [
      `<strong>5-stufiger Prozess der Personalsuche und -auswahl bei AlpenFresh:</strong><ol><li><strong>Festlegung des Anforderungsprofils:</strong> Welche fachlichen und persönlichen Qualifikationen braucht die Produktionsleiterin? (z.B. Lebensmitteltechnik, Führungserfahrung, HACCP-Kenntnisse)</li><li><strong>Personalsuche:</strong> Intern prüfen (Beförderung vorhandener Mitarbeiter?) → extern: AMS, karriere.at, LinkedIn, Aushang in der FH Kufstein</li><li><strong>Vorauswahl – Analyse der Bewerbungsunterlagen:</strong> Bewerbungsschreiben und Lebenslauf auf Vollständigkeit, Passung zum Anforderungsprofil und Berufserfahrung prüfen</li><li><strong>Auswahlverfahren:</strong> Strukturiertes Vorstellungsgespräch mit Fachfragen zur Lebensmittelproduktion, evtl. Probearbeitstag</li><li><strong>Personaleinstellung:</strong> Arbeitsvertrag, Dienstzettel, Einarbeitung (Onboarding-Plan für die ersten 3 Monate)</li></ol>`,
      `<strong>Maslow-Bedürfnispyramide – 5 Stufen mit AlpenFresh-Beispielen:</strong><ol><li><strong>Physiologische Bedürfnisse:</strong> Pünktliche Gehaltszahlung, Pausenraum mit Kaffee und Mahlzeiten</li><li><strong>Sicherheitsbedürfnisse:</strong> Unbefristeter Dienstvertrag, klare Arbeitsanweisungen, Schutzausrüstung in der Produktion</li><li><strong>Soziale Bedürfnisse:</strong> Gutes Teamklima, gemeinsame Betriebsausflüge, flache Hierarchie</li><li><strong>Wertschätzungsbedürfnisse:</strong> Lob durch die Geschäftsführerin, Einbindung in Entscheidungen, Anerkennung von Leistungen</li><li><strong>Selbstverwirklichung:</strong> Übernahme eigener Projekte (z.B. neue Produktlinie entwickeln), Weiterbildungsangebote</li></ol><br>Wenn Mitarbeiter trotz gutem Gehalt kündigen, fehlt meist Stufe 3–5 (Anerkennung, Entwicklung, Sinn der Arbeit).`,
      `<strong>Herzberg – Einordnung der Mitarbeiteraussage:</strong><br><table><tr><th>Aussage</th><th>Einordnung</th><th>Faktortyp</th></tr><tr><td>„Gehalt ist okay"</td><td>✅ vorhanden → keine Unzufriedenheit</td><td>Hygienefaktor</td></tr><tr><td>„Bekomme nie Feedback"</td><td>❌ fehlt → schafft Unzufriedenheit</td><td>Hygienefaktor (Führungsstil)</td></tr><tr><td>„Arbeit macht Spaß"</td><td>✅ vorhanden → schafft Zufriedenheit</td><td>Motivator (Arbeitsinhalt)</td></tr><tr><td>„Tolles Team"</td><td>✅ vorhanden → verhindert Unzufriedenheit</td><td>Hygienefaktor (Kollegialität)</td></tr><tr><td>„Büro eng und laut"</td><td>❌ fehlt → schafft Unzufriedenheit</td><td>Hygienefaktor (Arbeitsbedingungen)</td></tr></table><br>Fazit: Die Motivatoren sind positiv, aber fehlende Hygienefaktoren (kein Feedback, schlechte Arbeitsbedingungen) führen zur Unzufriedenheit. Nina Berger sollte zuerst diese beheben.`,
      `<strong>Betriebsrat bei AlpenFresh (18 Mitarbeiter):</strong><br><br>✅ <strong>Gründung möglich</strong> – ab 5 Arbeitnehmern haben Mitarbeiter das Recht, einen Betriebsrat zu gründen. Die Geschäftsführerin kann dies <em>nicht verbieten</em>.<br><br><strong>Aktiv wahlberechtigt</strong> (haben Wahlrecht): Alle Arbeitnehmer ab 16 Jahren → alle 18 Mitarbeiter von AlpenFresh.<br><strong>Passiv wahlberechtigt</strong> (können gewählt werden): Arbeitnehmer ab 18 Jahren, die seit mind. 6 Monaten im Betrieb sind.<br><br><strong>Anzahl der Betriebsratsmitglieder:</strong> Bei 10–19 Arbeitnehmern sind <strong>2 Mitglieder</strong> zu wählen.<br><br>Aufgaben des Betriebsrats: Mitbestimmung bei Arbeitszeiten, Mitwirkung bei Kündigungen, Interessenvertretung der Belegschaft.`
    ],
  fuehrung: [
      `<strong>Managementebenen bei TEAM 7 und normatives/strategisches/operatives Management:</strong><ul><li><strong>Topmanagement:</strong> Georg & Stefan Emprechtinger (Geschäftsführung) → normative Entscheidungen (Unternehmenswerte, Vision) und strategische Entscheidungen (Expansion in neue Märkte)</li><li><strong>Middle Management:</strong> Elisabeth Emprechtinger (Marketingleitung), Produktionsverantwortliche → setzen Strategie um, koordinieren Abteilungen</li><li><strong>Lower Management:</strong> Teamleiter in Produktion, Verkauf, Logistik → operative Aufgaben, direkte Mitarbeiterführung</li></ul><strong>Normativ</strong> = Grundsätze & Werte (langfristig). <strong>Strategisch</strong> = mittelfristige Planung (3–5 Jahre). <strong>Operativ</strong> = kurzfristiges Tagesgeschäft.`,
      `<strong>SWOT-Analyse AlpenFresh:</strong><br><table><tr><th>Stärken (intern)</th><th>Schwächen (intern)</th></tr><tr><td>• Bio-zertifiziert & regional<br>• Starke Markenidentität (Nachhaltigkeit)<br>• Direktvertrieb über eigenen Webshop</td><td>• Geringe Produktionskapazität<br>• Abhängigkeit von einzelnen Lieferanten<br>• Noch wenig Bekanntheit außerhalb Tirols</td></tr><tr><th>Chancen (extern)</th><th>Risiken (extern)</th></tr><tr><td>• Wachsende Nachfrage nach Bio-Produkten<br>• Expansion in den deutschen Markt<br>• Neue Vertriebskanäle (LEH, Abo-Box)</td><td>• Neue Konkurrenten im Bio-Segment<br>• Steigende Rohstoffpreise<br>• Wetterabhängige Ernten bei Zulieferern</td></tr></table><br><strong>SO-Strategie:</strong> Bio-Zertifizierung + wachsende Nachfrage → aktiv in deutschen Bio-Supermarkt expandieren (z.B. Kooperation mit denn's Biomarkt).<br><strong>WT-Strategie:</strong> Abhängigkeit von Lieferanten + Rohstoffpreisrisiko → 2. Lieferant für Schlüsselzutaten aufbauen, langfristige Lieferverträge abschließen.`,
      `<strong>Fünf-Kräfte-Modell von Porter – AlpenFresh:</strong><br><table><tr><th>Kraft</th><th>Einfluss bei AlpenFresh</th><th>Handlungsempfehlung</th></tr><tr><td>Rivalität unter Wettbewerbern</td><td>Bio-Markt wächst → viele neue Anbieter (mymuesli, Local Brands)</td><td>Differenzierung durch regionale Herkunft und persönliche Geschichte betonen</td></tr><tr><td>Verhandlungsmacht Lieferanten</td><td>Wenige zertifizierte Bio-Bauern in Tirol → hohe Abhängigkeit</td><td>Langfristige Verträge + 2. Lieferant aufbauen</td></tr><tr><td>Verhandlungsmacht Käufer</td><td>Endkunden im Online-Shop → niedrig; Supermarkt → hoch</td><td>Direktvertrieb (B2C) stärken, um Abhängigkeit von Händlern zu reduzieren</td></tr><tr><td>Bedrohung durch Substitutionsprodukte</td><td>Konventionelle Produkte deutlich günstiger</td><td>Kommunikation des Mehrwerts (Gesundheit, Regionalität, Umwelt)</td></tr><tr><td>Bedrohung durch neue Anbieter</td><td>Markteintrittsbarrieren niedrig im Bio-Food-Bereich</td><td>Marke frühzeitig etablieren, Kundenbindung (Newsletter, Community) aufbauen</td></tr></table>`,
      `<strong>Wahl der Aufbauorganisation für AlpenFresh (25 Mitarbeiter):</strong><br><br><strong>Empfehlung: Einliniensystem mit Stabsstellen</strong> (= Stabliniensystem)<br><br>Begründung: Mit 4 Abteilungen und 25 Mitarbeitern braucht AlpenFresh klare Verantwortlichkeiten (Einlinienprinzip). Gleichzeitig kann z.B. ein Qualitätsmanager oder Nachhaltigkeitsbeauftragter als Stabsstelle die Geschäftsführung beraten, ohne Weisungsbefugnis zu haben.<br><br><table><tr><th>Organisationsform</th><th>Vorteil</th><th>Nachteil</th></tr><tr><td>Einliniensystem</td><td>Klare Hierarchie, eindeutige Verantwortung</td><td>Lange Kommunikationswege bei vielen Ebenen</td></tr><tr><td>Stabliniensystem</td><td>Fachwissen wird gezielt eingebracht</td><td>Stabsstellen verursachen Kosten ohne Linienverantwortung</td></tr><tr><td>Mehrliniensystem</td><td>Kurze Kommunikationswege</td><td>Mehrere Vorgesetzte → Kompetenzkonflikte möglich</td></tr></table>`,
    ],
  investition: [
      `<strong>Kostenvergleichsrechnung AlpenFresh:</strong><br><table><tr><th>Position</th><th>Maschine A</th><th>Maschine B</th></tr><tr><td>Tatsächliche Menge</td><td>30.000 Stk.</td><td>35.000 Stk.</td></tr><tr><td>Kalk. AfA</td><td>(240.000 − 24.000) ÷ 8 = <strong>€ 27.000</strong></td><td>(260.000 − 26.000) ÷ 8 = <strong>€ 29.250</strong></td></tr><tr><td>Kalk. Zinsen</td><td>(240.000 + 24.000) ÷ 2 × 4% = <strong>€ 5.280</strong></td><td>(260.000 + 26.000) ÷ 2 × 4% = <strong>€ 5.720</strong></td></tr><tr><td>Variable Kosten</td><td>0,45 × 30.000 = <strong>€ 13.500</strong></td><td>0,40 × 35.000 = <strong>€ 14.000</strong></td></tr><tr><td>Fixkosten</td><td><strong>€ 8.000</strong></td><td><strong>€ 12.000</strong></td></tr><tr><td><strong>Gesamtkosten</strong></td><td><strong>€ 53.780</strong></td><td><strong>€ 60.970</strong></td></tr><tr><td><strong>Stückkosten</strong></td><td>53.780 ÷ 30.000 = <strong>€ 1,79/Stk.</strong></td><td>60.970 ÷ 35.000 = <strong>€ 1,74/Stk.</strong></td></tr></table><br>→ Gesamtkosten: <strong>Maschine A günstiger</strong>. Stückkosten: Maschine B günstiger (wegen größerer Menge). Da AlpenFresh nicht die volle Kapazität von B benötigt, ist <strong>Maschine A zu empfehlen</strong>.`,
      `<strong>Finanzierungsarten AlpenFresh:</strong><br><table><tr><th>Situation</th><th>Innen/Außen</th><th>Eigen/Fremd</th></tr><tr><td>(a) Lieferantenrechnung in 3 Monaten</td><td>Außen</td><td>Fremd (Lieferantenkredit)</td></tr><tr><td>(b) Geschäftsführerin legt € 30.000 ein</td><td>Außen</td><td>Eigen (Einlagenfinanzierung)</td></tr><tr><td>(c) Abgeschriebene Maschine verkauft</td><td>Innen</td><td>Eigen (Umschichtungsfinanzierung)</td></tr><tr><td>(d) Bankkredit € 100.000</td><td>Außen</td><td>Fremd (Kreditfinanzierung)</td></tr></table>`,
      `<strong>Vier Crowdfunding-Modelle:</strong><br><table><tr><th>Modell</th><th>Prinzip</th><th>Beispiel für AlpenFresh</th></tr><tr><td>Donation-based</td><td>Spenden ohne Gegenleistung</td><td>Spende für nachhaltiges Verpackungsprojekt</td></tr><tr><td>Reward-based</td><td>Gegenleistung = Produkt/Erlebnis</td><td>Unterstützer bekommen die neue Produktlinie als Erste</td></tr><tr><td>Lending-based</td><td>Kredit von vielen Privatpersonen</td><td>Crowd leiht AlpenFresh € 50.000 für neue Maschine, bekommt Zinsen</td></tr><tr><td>Equity-based</td><td>Unternehmensanteile im Austausch für Kapital</td><td>Investoren erhalten 5 % Unternehmensanteil</td></tr></table><br>Empfehlung für AlpenFresh: <strong>Reward-based</strong> – stärkt gleichzeitig die Community und Kundenbindung, ohne Schulden oder Unternehmensanteile abzugeben.`,
      `<strong>Kennzahlenanalyse AlpenFresh:</strong><br><br><strong>Eigenkapitalquote</strong> = EK ÷ Gesamtkapital × 100<br>= 190.000 ÷ 350.000 × 100 = <strong>54,3 %</strong> → sehr solide, Faustregel ≥ 30 %<br><br><strong>Liquidität 1. Grades</strong> = flüssige Mittel ÷ kurzfristiges FK × 100<br>= 25.000 ÷ 60.000 × 100 = <strong>41,7 %</strong> → unter 100 %, Vorsicht bei plötzlichen Zahlungen<br><br><strong>Liquidität 2. Grades</strong> = (flüssige Mittel + Forderungen) ÷ kurzfristiges FK × 100<br>= (25.000 + 35.000) ÷ 60.000 × 100 = <strong>100 %</strong> → genau ausreichend, Sollwert ≥ 100 %<br><br><strong>Anlagendeckung</strong> = (EK + langfr. FK) ÷ Anlagevermögen × 100<br>= (190.000 + 100.000) ÷ 250.000 × 100 = <strong>116 %</strong> → gut, Anlagevermögen ist langfristig gedeckt`
    ],
  expansion: [
      `<table><tr><th>Strategie</th><th>Kosten</th><th>Risiko</th><th>Kontrolle</th></tr><tr><td><strong>Direktexport</strong></td><td>Gering</td><td>Gering</td><td>Mittel</td></tr><tr><td><strong>Indirekter Export</strong> (Handelsvertreter)</td><td>Gering</td><td>Gering</td><td>Gering</td></tr><tr><td><strong>Tochtergesellschaft</strong></td><td>Hoch</td><td>Hoch</td><td>Hoch</td></tr><tr><td><strong>Joint Venture</strong></td><td>Mittel</td><td>Mittel</td><td>Mittel</td></tr></table><br>→ Für AlpenFresh als kleines Start-up: <strong>Direktexport oder Handelsvertreter</strong> als erster Schritt – geringes Risiko, überschaubare Kosten.`,
      `<strong>Länderanalyse Südtirol:</strong><ul><li><strong>Marktpotenzial:</strong> 530.000 Einwohner, hohe Affinität zu regionalen Bio-Produkten, Nähe zu Österreich</li><li><strong>Kulturelle Nähe:</strong> Deutschsprachig, ähnliche Essgewohnheiten, bekannte Marken aus Österreich sind akzeptiert</li><li><strong>Sprachliche Vorteile:</strong> Kein Übersetzungsaufwand für Verpackung und Marketing</li><li><strong>Rechtliche Besonderheiten:</strong> EU-Mitglied (kein Zoll, keine Einfuhrabgaben), italienische MwSt. auf Lebensmittel: 4 % (Österreich: 10 %) → günstig</li><li><strong>Fazit:</strong> Idealer erster Exportmarkt für AlpenFresh!</li></ul>`,
      `<strong>Wechselkursrisiko Schweiz:</strong><br>Ausgangssituation: AlpenFresh verkauft für CHF 3,20, Kurs EUR/CHF = 0,95<br>Euro-Erlös: CHF 3,20 × 0,95 = <strong>€ 3,04</strong><br><br>Kurs fällt auf EUR/CHF = 0,90:<br>Euro-Erlös: CHF 3,20 × 0,90 = <strong>€ 2,88</strong><br><br>Verlust: € 3,04 − € 2,88 = <strong>€ 0,16 pro Stück</strong> (−5,3 %)<br>Bei 10.000 Stück/Monat = Erlösrückgang von <strong>€ 1.600/Monat</strong> ohne Kursänderung beim Produkt!`,
      `<strong>Empfehlung: Zuerst Südtirol</strong><br>Begründung: (1) Kein Währungsrisiko (beide in €), (2) kulturelle und sprachliche Nähe → geringerer Marketing-Aufwand, (3) EU-Binnenmarkt → keine Zollhürden, (4) Bio-Affinität der Südtiroler, (5) Test für internationales Vorgehen mit überschaubarem Risiko.<br><br>Die Schweiz ist als zweiter Schritt sinnvoll, wenn Südtirol erfolgreich war – aber erst dann, wenn AlpenFresh das Wechselkursrisiko absichern kann.`
    ],
  produktion: [
      `<strong>Wirtschaftssektor und Betriebstyp:</strong><br><br>AlpenFresh gehört zum <strong>sekundären Sektor</strong> (produzierendes Gewerbe), weil das Unternehmen Rohstoffe (Haferflocken, Früchte, Nüsse) zu fertigen Produkten (AlpenBars, AlpenMüsli) verarbeitet.<br><br><strong>Konsumgüterbetrieb</strong> vs. <strong>Investitionsgüterbetrieb</strong>:<ul><li><strong>Konsumgüterbetriebe</strong> produzieren Waren, die direkt von Endverbrauchern genutzt werden (z.B. Lebensmittel, Kleidung).</li><li><strong>Investitionsgüterbetriebe</strong> produzieren Güter, die von anderen Unternehmen als Produktionsmittel verwendet werden (z.B. Maschinen, Stahlbleche).</li></ul>→ AlpenFresh ist ein <strong>Konsumgüterbetrieb</strong>, weil AlpenBars und AlpenMüsli direkt von Konsumenten gegessen werden.`,
      `<strong>Standortfaktoren für AlpenFresh:</strong><br><table><tr><th>Art</th><th>Faktor</th><th>Wörgl</th><th>Salzburg</th></tr><tr><td rowspan="2"><strong>Beschaffungs-orientiert</strong></td><td>Nähe zu Rohstofflieferanten</td><td>✅ Koflerhof Tirol direkt nebenan</td><td>⚠️ längere Transportwege</td></tr><tr><td>Transportinfrastruktur</td><td>✅ Autobahn A12 vorhanden</td><td>✅ sehr gute Verkehrsanbindung</td></tr><tr><td rowspan="2"><strong>Produktions-orientiert</strong></td><td>Arbeitskräfte / Fachpersonal</td><td>⚠️ Fachkräftemangel in Tirol</td><td>✅ größeres Einzugsgebiet</td></tr><tr><td>Energiekosten</td><td>✅ vergleichbar</td><td>✅ vergleichbar</td></tr><tr><td rowspan="2"><strong>Absatz-orientiert</strong></td><td>Nähe zu Kunden/Händlern</td><td>⚠️ Hauptmärkte Wien, München weiter</td><td>✅ zentraler in Österreich</td></tr><tr><td>Image / Regionalität</td><td>✅ „Tiroler Bio" als USP</td><td>⚠️ verliert Tiroler Herkunftsvorteil</td></tr></table><br>Empfehlung: <strong>Wörgl modernisieren</strong> – der Tiroler Ursprung ist ein wesentliches Verkaufsargument für Bio-Produkte und sollte nicht aufgegeben werden.`,
      `<strong>Brutto- und Nettobedarf Haferflocken:</strong><br><br><strong>Schritt 1 – Bruttobedarf:</strong><br>80.000 AlpenBars × 120 g = <strong>9.600.000 g = 9.600 kg</strong><br><br><strong>Schritt 2 – Lagerbestand abziehen:</strong><br>Lagerbestand: 4.200 kg<br><br><strong>Schritt 3 – Nettobedarf:</strong><br>9.600 kg − 4.200 kg = <strong>5.400 kg</strong><br><br>→ AlpenFresh muss <strong>5.400 kg Haferflocken</strong> beim Koflerhof nachbestellen, um den Großauftrag erfüllen zu können.`,
      `<strong>Just-in-time vs. Vorratsbeschaffung für AlpenFresh:</strong><br><table><tr><th></th><th>Just-in-time</th><th>Vorratsbeschaffung</th></tr><tr><td><strong>Prinzip</strong></td><td>Material wird erst bei Bedarf bestellt und geliefert</td><td>Großer Lagerbestand als Puffer</td></tr><tr><td><strong>Vorteile</strong></td><td>• Keine Lagerkosten<br>• Immer frische Rohstoffe (wichtig bei Bio!)</td><td>• Sicherheit bei Lieferengpässen<br>• Mengenrabatte beim Einkauf möglich</td></tr><tr><td><strong>Nachteile</strong></td><td>• Abhängig von zuverlässigem Lieferanten<br>• Kein Puffer bei Lieferverzögerungen</td><td>• Hohe Lagerkosten<br>• Verderb möglich (Haferflocken, Früchte)</td></tr></table><br><strong>Empfehlung für AlpenFresh:</strong> Da AlpenFresh mit Bio-Rohstoffen arbeitet, die leicht verderben können, und der Hauptlieferant Koflerhof regional und verlässlich ist, empfiehlt sich ein <strong>Mix</strong>: Just-in-time für frische Zutaten, kleine Vorräte (Sicherheitsbestand) für Basisrohstoffe wie Haferflocken.`
    ],
  finanzplan: [
      `<strong>Break-even-Analyse AlpenFresh:</strong><br><br>Deckungsbeitrag/Stk. = € 3,20 − € 1,80 = <strong>€ 1,40/Stk.</strong><br>Break-even-Menge = € 84.000 ÷ € 1,40 = <strong>60.000 Stk.</strong><br>Break-even-Umsatz = 60.000 × € 3,20 = <strong>€ 192.000</strong><br><br>Sicherheitsabstand: 80.000 − 60.000 = <strong>20.000 Stk.</strong> = 25 % der Planmenge<br>Gewinn bei Planmenge: 20.000 × € 1,40 = <strong>€ 28.000/Jahr</strong><br><br>Beurteilung: Die geplante Menge von 80.000 Stk. liegt 25 % über dem Break-even. Das ist ein solider Puffer – selbst wenn die Absatzmenge um 20 % sinkt, macht AlpenFresh noch keinen Verlust.`,
      `<strong>Erfolgsplanung</strong> zeigt, ob ein Unternehmen Gewinn oder Verlust macht (Erträge − Aufwendungen). <strong>Liquiditätsplanung</strong> zeigt, ob das Unternehmen zu jedem Zeitpunkt zahlungsfähig ist (Einzahlungen − Auszahlungen).<br><br>Eine Erfolgsplanung allein reicht nicht, weil ein Unternehmen trotz Gewinn zahlungsunfähig sein kann:<br><strong>Beispiel:</strong> AlpenFresh liefert im Jänner Ware im Wert von € 30.000 auf Ziel (Zahlung erst in 60 Tagen). In dieser Zeit müssen aber Gehälter, Miete und Lieferanten sofort bezahlt werden. Das Unternehmen macht buchhalterisch Gewinn, hat aber kurzfristig kein Geld – Liquiditätsproblem!`,
      `<strong>Liquiditätsplan Q1 AlpenFresh:</strong><br><table><tr><th>Position</th><th>Jänner</th><th>Februar</th><th>März</th></tr><tr><td>Anfangsbestand</td><td>€ 12.000</td><td>?</td><td>?</td></tr><tr><td>+ Einzahlungen</td><td>€ 18.000</td><td>€ 22.000</td><td>€ 26.000</td></tr><tr><td>− Fixe Auszahlungen</td><td>€ 8.500</td><td>€ 8.500</td><td>€ 8.500</td></tr><tr><td>− Kreditrate</td><td>€ 1.800</td><td>€ 1.800</td><td>€ 1.800</td></tr><tr><td>− Wareneinkauf</td><td>€ 9.000</td><td>€ 11.000</td><td>€ 13.000</td></tr><tr><td><strong>Über-/Unterdeckung</strong></td><td><strong>−€ 1.300</strong></td><td><strong>+€ 700</strong></td><td><strong>+€ 2.700</strong></td></tr><tr><td><strong>Endbestand</strong></td><td><strong>€ 10.700</strong></td><td><strong>€ 11.400</strong></td><td><strong>€ 14.100</strong></td></tr></table><br>Jänner hat eine Unterdeckung (−€ 1.300), aber der Anfangsbestand reicht aus. Ab Februar dreht es ins Positive.`,
      `<strong>Eigenkapitalquote:</strong><br>EK-Quote = EK ÷ Gesamtkapital × 100<br>= € 95.000 ÷ (€ 95.000 + € 65.000) × 100<br>= € 95.000 ÷ € 160.000 × 100 = <strong>59,4 %</strong><br><br>Relevanz für die Kreditvergabe: Eine hohe EK-Quote zeigt der Bank, dass das Unternehmen solide finanziert ist und die Eigentümer selbst Risiko tragen. Faustregel: <strong>≥ 30 % EK-Quote</strong> gilt als Mindestanforderung. AlpenFresh liegt mit 59,4 % sehr gut und hat gute Chancen auf den Kredit.`
    ],
};