const LOESUNGEN_HAK2 = {
  gruendung: [
      `<strong>Vorteile der Selbstständigkeit:</strong> Selbstbestimmung (eigene Ideen umsetzen), Entscheidungsfreiheit, hohe Motivation, Gewinn bleibt beim Unternehmer, freie Zeiteinteilung.<br><br><strong>Nachteile:</strong> Aufgabe einer sicheren Anstellung, finanzielles Risiko (Haftung mit Privatvermögen bei e.U.), hoher Leistungsdruck, unregelmäßiges Einkommen, hoher Zeitaufwand.`,
      `Ein <strong>Businessplan</strong> enthält: (1) Executive Summary, (2) Unternehmensbeschreibung & Geschäftsidee, (3) Markt- und Wettbewerbsanalyse, (4) Marketing- und Vertriebsstrategie, (5) Organisations- und Rechtsform, (6) Finanzplanung (Umsatz-, Kosten-, Liquiditätsplan), (7) Risikoanalyse. Er dient als Entscheidungsgrundlage für Gründer selbst, Banken und Investoren.`,
      `<strong>Ja</strong>, AlpenFresh ist ein Unternehmer im Sinne des UGB, wenn folgende Kriterien erfüllt sind: (1) Selbstständige wirtschaftliche Tätigkeit – Lisa entscheidet eigenverantwortlich, (2) auf Dauer angelegt – kein einmaliges Geschäft, (3) nach außen am Markt tätig. Die Gewinnerzielungsabsicht ist kein zwingend notwendiges Kriterium (auch gemeinnützige Organisationen können Unternehmer sein).`,
      `<strong>Empfehlung: GmbH</strong><br><ul><li><strong>e.U.:</strong> Einfache Gründung, kein Mindestkapital, aber volle Haftung mit Privatvermögen → riskant bei wachsendem Unternehmen</li><li><strong>GmbH:</strong> Mindestkapital € 10.000, Haftung auf Stammkapital beschränkt, höhere Gründungskosten (Notar, Firmenbuch), aber Privatvermögen geschützt → empfehlenswert ab ernsthafter Geschäftstätigkeit</li><li><strong>OG:</strong> Mindestens 2 Gesellschafter, alle haften unbeschränkt → weniger geeignet</li></ul>Für AlpenFresh empfiehlt sich die <strong>GmbH</strong> wegen der Haftungsbeschränkung.`
    ],
  marketing: [
      `<strong>Marketing-Mix (4 P's) für die AlpenBar:</strong><ul><li><strong>Produkt:</strong> Bio-Müsliriegel mit Tiroler Heumilchschokolade, regionale Zutaten, nachhaltige Verpackung, Zertifizierungen (AMA, Bio Austria)</li><li><strong>Preis:</strong> € 2,49 → Premiumpreis-Strategie (Bio-Qualität rechtfertigt höheren Preis als Standardriegel)</li><li><strong>Distribution (Place):</strong> Supermärkte (REWE, SPAR), Bio-Läden, eigener Onlineshop, Tankstellen/Kioske</li><li><strong>Kommunikation (Promotion):</strong> Social Media (Instagram, TikTok), regionale Influencer, Messen (BioFach), Verkostungsaktionen</li></ul>`,
      `<strong>Marktforschung:</strong> Systematische Sammlung und Auswertung von Informationen über Märkte, Kunden und Konkurrenten.<br><br><strong>Primärforschung</strong> (neue Daten erheben): z.B. AlpenFresh führt eine Online-Umfrage unter 200 Personen zur Zahlungsbereitschaft durch.<br><strong>Sekundärforschung</strong> (vorhandene Daten nutzen): z.B. AlpenFresh wertet Statistik Austria-Daten zum Bio-Lebensmittelkonsum aus oder nutzt Marktberichte von Branchenverbänden.`,
      `<strong>Budgetverteilung € 30.000:</strong><ul><li>Instagram/TikTok Ads: € 10.000 (33%) – erreicht Zielgruppe 25–45 direkt</li><li>Verkostungsaktionen in Supermärkten: € 8.000 (27%) – direkte Kaufentscheidung am POS</li><li>Influencer Marketing (Mikro-Influencer, regional): € 6.000 (20%) – authentisch, kostengünstig</li><li>Printmaterial (Aufsteller, Flyer): € 3.000 (10%) – für POS-Präsenz</li><li>PR / Pressearbeit: € 3.000 (10%) – Artikel in Regionalpresse, Bio-Magazinen</li></ul>`,
      `<strong>Break-even-Berechnung:</strong><br>Stückdeckungsbeitrag = VKP − variable Kosten = € 2,49 − € 0,85 = <strong>€ 1,64</strong><br>Break-even-Menge = Fixkosten ÷ Stückdeckungsbeitrag = € 30.000 ÷ € 1,64 = <strong>18.293 Stück</strong><br>→ AlpenFresh muss mindestens 18.293 AlpenBars verkaufen, bevor die Marketingkosten gedeckt sind und Gewinn entsteht.`
    ],
  preisgestaltung: [
      `<strong>Deckungsbeitragsrechnung:</strong><br>DB/Stück = VKP − variable Kosten = € 2,49 − € 0,85 = <strong>€ 1,64</strong><br>Gesamtdeckungsbeitrag = € 1,64 × 15.000 Stück = <strong>€ 24.600/Monat</strong><br>Fixkosten: € 12.000/Monat<br>Gewinn = € 24.600 − € 12.000 = <strong>€ 12.600/Monat</strong> ✓ → Ja, Gewinn ist möglich!`,
      `<strong>Cost-Plus-Pricing Berechnung:</strong><br>Variable Kosten/Stück: € 0,85<br>Fixkosten/Stück: € 12.000 ÷ 15.000 = € 0,80<br>Gesamtkosten/Stück: € 0,85 + € 0,80 = € 1,65<br>Aufschlag 40 %: € 1,65 × 1,40 = <strong>€ 2,31</strong><br>→ Kalkulierter Preis: ca. € 2,31. Da die Konkurrenz bis zu € 2,80 verlangt, ist € 2,49 als Premiumpreis gut positioniert.`,
      `<table><tr><th>Strategie</th><th>Vorteile</th><th>Nachteile</th></tr><tr><td><strong>Niedrigpreis</strong></td><td>Hohe Absatzmenge, schnelle Marktdurchdringung</td><td>Schadet dem Bio-Image, gefährdet Deckungsbeitrag</td></tr><tr><td><strong>Premiumpreis</strong></td><td>Passt zum Bio-Markenwert, höhere Margen</td><td>Geringere Absatzmenge, Kunden müssen überzeugt werden</td></tr><tr><td><strong>Konkurrenzorientiert</strong></td><td>Marktkonform, leicht verständlich</td><td>Reagiert nur, keine eigenständige Positionierung</td></tr></table><br>→ <strong>Empfehlung: Premiumpreis (€ 2,49)</strong> passt zum regionalen Bio-Image von AlpenFresh.`,
      `<strong>Break-even bei verschiedenen Preisen:</strong><br>Bei VKP € 2,49: DB = € 1,64 → Break-even = € 12.000 ÷ € 1,64 = <strong>7.317 Stück</strong><br>Bei VKP € 2,99: DB = € 2,14 → Break-even = € 12.000 ÷ € 2,14 = <strong>5.607 Stück</strong><br>→ Bei € 2,99 wird die Gewinnschwelle früher erreicht → <strong>geringeres Risiko</strong>. Aber: Höherer Preis kann die Absatzmenge senken – das muss abgewogen werden.`
    ],
  personal: [
      `<strong>5-stufiger Prozess der Personalsuche und -auswahl bei AlpenFresh:</strong><ol><li><strong>Festlegung des Anforderungsprofils:</strong> Welche fachlichen und persönlichen Qualifikationen braucht die Produktionsleiterin? (z.B. Lebensmitteltechnik, Führungserfahrung, HACCP-Kenntnisse)</li><li><strong>Personalsuche:</strong> Intern prüfen (Beförderung vorhandener Mitarbeiter?) → extern: AMS, karriere.at, LinkedIn, Aushang in der FH Kufstein</li><li><strong>Vorauswahl – Analyse der Bewerbungsunterlagen:</strong> Bewerbungsschreiben und Lebenslauf auf Vollständigkeit, Passung zum Anforderungsprofil und Berufserfahrung prüfen</li><li><strong>Auswahlverfahren:</strong> Strukturiertes Vorstellungsgespräch mit Fachfragen zur Lebensmittelproduktion, evtl. Probearbeitstag</li><li><strong>Personaleinstellung:</strong> Arbeitsvertrag, Dienstzettel, Einarbeitung (Onboarding-Plan für die ersten 3 Monate)</li></ol>`,
      `<strong>Maslow-Bedürfnispyramide – 5 Stufen mit AlpenFresh-Beispielen:</strong><ol><li><strong>Physiologische Bedürfnisse:</strong> Pünktliche Gehaltszahlung, Pausenraum mit Kaffee und Mahlzeiten</li><li><strong>Sicherheitsbedürfnisse:</strong> Unbefristeter Dienstvertrag, klare Arbeitsanweisungen, Schutzausrüstung in der Produktion</li><li><strong>Soziale Bedürfnisse:</strong> Gutes Teamklima, gemeinsame Betriebsausflüge, flache Hierarchie</li><li><strong>Wertschätzungsbedürfnisse:</strong> Lob durch die Geschäftsführerin, Einbindung in Entscheidungen, Anerkennung von Leistungen</li><li><strong>Selbstverwirklichung:</strong> Übernahme eigener Projekte (z.B. neue Produktlinie entwickeln), Weiterbildungsangebote</li></ol><br>Wenn Mitarbeiter trotz gutem Gehalt kündigen, fehlt meist Stufe 3–5 (Anerkennung, Entwicklung, Sinn der Arbeit).`,
      `<strong>Herzberg – Einordnung der Mitarbeiteraussage:</strong><br><table><tr><th>Aussage</th><th>Einordnung</th><th>Faktortyp</th></tr><tr><td>„Gehalt ist okay"</td><td>✅ vorhanden → keine Unzufriedenheit</td><td>Hygienefaktor</td></tr><tr><td>„Bekomme nie Feedback"</td><td>❌ fehlt → schafft Unzufriedenheit</td><td>Hygienefaktor (Führungsstil)</td></tr><tr><td>„Arbeit macht Spaß"</td><td>✅ vorhanden → schafft Zufriedenheit</td><td>Motivator (Arbeitsinhalt)</td></tr><tr><td>„Tolles Team"</td><td>✅ vorhanden → verhindert Unzufriedenheit</td><td>Hygienefaktor (Kollegialität)</td></tr><tr><td>„Büro eng und laut"</td><td>❌ fehlt → schafft Unzufriedenheit</td><td>Hygienefaktor (Arbeitsbedingungen)</td></tr></table><br>Fazit: Die Motivatoren sind positiv, aber fehlende Hygienefaktoren (kein Feedback, schlechte Arbeitsbedingungen) führen zur Unzufriedenheit. Nina Berger sollte zuerst diese beheben.`,
      `<strong>Betriebsrat bei AlpenFresh (18 Mitarbeiter):</strong><br><br>✅ <strong>Gründung möglich</strong> – ab 5 Arbeitnehmern haben Mitarbeiter das Recht, einen Betriebsrat zu gründen. Die Geschäftsführerin kann dies <em>nicht verbieten</em>.<br><br><strong>Aktiv wahlberechtigt</strong> (haben Wahlrecht): Alle Arbeitnehmer ab 16 Jahren → alle 18 Mitarbeiter von AlpenFresh.<br><strong>Passiv wahlberechtigt</strong> (können gewählt werden): Arbeitnehmer ab 18 Jahren, die seit mind. 6 Monaten im Betrieb sind.<br><br><strong>Anzahl der Betriebsratsmitglieder:</strong> Bei 10–19 Arbeitnehmern sind <strong>2 Mitglieder</strong> zu wählen.<br><br>Aufgaben des Betriebsrats: Mitbestimmung bei Arbeitszeiten, Mitwirkung bei Kündigungen, Interessenvertretung der Belegschaft.`
    ],
  recht: [
      `<table><tr><th>Kriterium</th><th>e.U.</th><th>GmbH</th><th>OG</th></tr><tr><td>Haftung</td><td>Unbeschränkt (Privatvermögen)</td><td>Beschränkt auf Stammkapital</td><td>Unbeschränkt, solidarisch</td></tr><tr><td>Mindestkapital</td><td>Keines</td><td>€ 10.000</td><td>Keines</td></tr><tr><td>Gründer</td><td>1 Person</td><td>Mind. 1 Person</td><td>Mind. 2 Personen</td></tr><tr><td>Firmenbuch</td><td>Ab € 700.000 Umsatz Pflicht</td><td>Immer Pflicht</td><td>Immer Pflicht</td></tr></table>`,
      `<strong>Bestandteile eines Kaufvertrags:</strong><ol><li><strong>Ware/Leistung:</strong> genaue Bezeichnung des Produkts (z.B. „Bio-Haferflocken, Qualität A")</li><li><strong>Menge:</strong> z.B. 2.000 kg</li><li><strong>Preis:</strong> z.B. € 1,20/kg, netto exkl. MwSt.</li><li><strong>Liefertermin/-ort:</strong> z.B. „15.04. frei Haus Wien"</li><li><strong>Zahlungsbedingungen:</strong> z.B. „30 Tage netto, 2 % Skonto bei Zahlung in 10 Tagen"</li><li><strong>Gewährleistung:</strong> 2 Jahre gesetzliche Gewährleistung</li></ol>`,
      `<strong>Muster-Bestellschreiben:</strong><br><pre style="font-size:0.8rem;background:#f8fafc;border-radius:6px;padding:10px;line-height:1.8">AlpenFresh GmbH · Innsbrucker Straße 5 · 6060 Hall in Tirol
An: Mühlviertler Getreidemühle GmbH, Freistadt

Bestellung Nr. 2024-047
Datum: 15.04.2024

Sehr geehrte Damen und Herren,

wir bestellen hiermit folgende Ware:

Position: Bio-Haferflocken, zart, AMA-zertifiziert
Menge: 2.000 kg
Einzelpreis: € 1,20/kg, netto exkl. 10 % MwSt.
Gesamtbetrag: € 2.400,00 netto

Gewünschter Liefertermin: 30.04.2024
Lieferadresse: AlpenFresh GmbH, Produktion, Innsbrucker Str. 5, 6060 Hall
Zahlungsbedingung: 30 Tage netto

Mit freundlichen Grüßen,
Lisa Hofer, Geschäftsführerin AlpenFresh GmbH</pre>`,
      `<strong>Rechtsfolgen bei Vertragsverletzung:</strong><br><ul><li><strong>Mahnung:</strong> Formlose Aufforderung zur Leistungserfüllung (1. Mahnung meist freundlich, 2. mit Fristsetzung, 3. mit Androhung rechtlicher Schritte)</li><li><strong>Klage:</strong> Klage beim zuständigen Bezirks- oder Handelsgericht auf Erfüllung oder Schadenersatz</li><li><strong>Inkasso:</strong> Beauftragung eines Inkassobüros für die außergerichtliche Forderungseintreibung (günstiger als Klage)</li><li><strong>Rücktritt:</strong> Bei Nichtlieferung oder mangelhafter Ware kann vom Vertrag zurückgetreten werden</li></ul>`
    ],
  expansion: [
      `<table><tr><th>Strategie</th><th>Kosten</th><th>Risiko</th><th>Kontrolle</th></tr><tr><td><strong>Direktexport</strong></td><td>Gering</td><td>Gering</td><td>Mittel</td></tr><tr><td><strong>Indirekter Export</strong> (Handelsvertreter)</td><td>Gering</td><td>Gering</td><td>Gering</td></tr><tr><td><strong>Tochtergesellschaft</strong></td><td>Hoch</td><td>Hoch</td><td>Hoch</td></tr><tr><td><strong>Joint Venture</strong></td><td>Mittel</td><td>Mittel</td><td>Mittel</td></tr></table><br>→ Für AlpenFresh als kleines Start-up: <strong>Direktexport oder Handelsvertreter</strong> als erster Schritt – geringes Risiko, überschaubare Kosten.`,
      `<strong>Länderanalyse Südtirol:</strong><ul><li><strong>Marktpotenzial:</strong> 530.000 Einwohner, hohe Affinität zu regionalen Bio-Produkten, Nähe zu Österreich</li><li><strong>Kulturelle Nähe:</strong> Deutschsprachig, ähnliche Essgewohnheiten, bekannte Marken aus Österreich sind akzeptiert</li><li><strong>Sprachliche Vorteile:</strong> Kein Übersetzungsaufwand für Verpackung und Marketing</li><li><strong>Rechtliche Besonderheiten:</strong> EU-Mitglied (kein Zoll, keine Einfuhrabgaben), italienische MwSt. auf Lebensmittel: 4 % (Österreich: 10 %) → günstig</li><li><strong>Fazit:</strong> Idealer erster Exportmarkt für AlpenFresh!</li></ul>`,
      `<strong>Wechselkursrisiko Schweiz:</strong><br>Ausgangssituation: AlpenFresh verkauft für CHF 3,20, Kurs EUR/CHF = 0,95<br>Euro-Erlös: CHF 3,20 × 0,95 = <strong>€ 3,04</strong><br><br>Kurs fällt auf EUR/CHF = 0,90:<br>Euro-Erlös: CHF 3,20 × 0,90 = <strong>€ 2,88</strong><br><br>Verlust: € 3,04 − € 2,88 = <strong>€ 0,16 pro Stück</strong> (−5,3 %)<br>Bei 10.000 Stück/Monat = Erlösrückgang von <strong>€ 1.600/Monat</strong> ohne Kursänderung beim Produkt!`,
      `<strong>Empfehlung: Zuerst Südtirol</strong><br>Begründung: (1) Kein Währungsrisiko (beide in €), (2) kulturelle und sprachliche Nähe → geringerer Marketing-Aufwand, (3) EU-Binnenmarkt → keine Zollhürden, (4) Bio-Affinität der Südtiroler, (5) Test für internationales Vorgehen mit überschaubarem Risiko.<br><br>Die Schweiz ist als zweiter Schritt sinnvoll, wenn Südtirol erfolgreich war – aber erst dann, wenn AlpenFresh das Wechselkursrisiko absichern kann.`
    ],
};