const LOESUNGEN_HLW2 = {
  gruendung: [
      `<strong>Vorteile:</strong> Selbstbestimmung, eigene Ideen umsetzen, Gewinn bleibt beim Unternehmer, freie Zeiteinteilung, hohe Motivation.<br><br><strong>Nachteile:</strong> Finanzielles Risiko, Haftung mit Privatvermögen, unregelmäßiges Einkommen, hoher Arbeitseinsatz, kein Anspruch auf Urlaub/Krankenstand wie Angestellte.`,
      `Ein <strong>Businessplan</strong> ist ein schriftliches Konzept für eine Unternehmensgründung. Er ist wichtig, weil er (1) den Gründer zwingt, alles durchzudenken, (2) als Grundlage für Bankkredite dient und (3) den Weg zum Erfolg strukturiert. Bestandteile: Geschäftsidee, Zielgruppe, Marktanalyse, Marketing, Finanzplanung, Risikoanalyse.`,
      `<strong>5 Gründungsschritte für AlpenFresh:</strong><ol><li>Geschäftsidee entwickeln und prüfen (Marktanalyse)</li><li>Businessplan erstellen</li><li>Rechtsform wählen (z.B. GmbH) und Stammkapital einzahlen</li><li>Gewerbeanmeldung bei der Gewerbebehörde</li><li>Eintragung ins Firmenbuch, Anmeldung beim Finanzamt (Steuernummer, UID)</li></ol>`,
      `Die <strong>Wirtschaftskammer Österreich (WKO)</strong> ist die gesetzliche Interessenvertretung der österreichischen Unternehmen. Sie bietet: kostenloses Gründerservice mit Beratung, Informationen zu Rechtsformen und Gewerberecht, Checklisten für Gründer. Jeder Unternehmer in Österreich ist automatisch WKO-Pflichtmitglied (Beitragspflicht!).`
    ],
  marketing: [
      `<strong>Marketing-Mix (4 P's) für die AlpenBar:</strong><ul><li><strong>Produkt:</strong> Bio-Müsliriegel mit Tiroler Heumilchschokolade, regional und nachhaltig</li><li><strong>Preis:</strong> € 2,49 – Premiumpreis, passend zum Bio-Image</li><li><strong>Distribution (Place):</strong> Supermärkte (SPAR, REWE), Bio-Läden, Onlineshop</li><li><strong>Kommunikation (Promotion):</strong> Social Media, Verkostungen, regionale Werbung</li></ul>`,
      `<strong>Primärforschung:</strong> Neue Daten werden selbst erhoben (z.B. Umfrage, Interview, Beobachtung). Teurer, aber genau auf die Fragestellung zugeschnitten.<br>Beispiel AlpenFresh: Online-Umfrage zur Zahlungsbereitschaft.<br><br><strong>Sekundärforschung:</strong> Bereits vorhandene Daten werden genutzt (z.B. Statistiken, Studien). Günstiger, aber nicht immer aktuell.<br>Beispiel AlpenFresh: Statistik Austria-Daten zum Bio-Konsum in Österreich.`,
      `<strong>Geeignete Social-Media-Kanäle für 25–45 Jahre:</strong><ul><li><strong>Instagram:</strong> Visuelle Plattform, ideal für Food-Produkte, hohe Nutzung in der Zielgruppe</li><li><strong>Facebook:</strong> Erreicht gut die Gruppe 35–45, geeignet für Community und Events</li><li><strong>TikTok:</strong> Wächst stark, eher 20–35 Jahre, aber gutes virales Potenzial</li></ul>LinkedIn und Twitter weniger geeignet – zu business-orientiert für ein Konsumprodukt.`,
      `<strong>Zielgruppensegmentierung</strong> = Aufteilung des Gesamtmarktes in Gruppen mit ähnlichen Merkmalen. Kriterien: demografisch (Alter, Geschlecht), geografisch (Region), psychografisch (Werte, Lebensstil), verhaltensorientiert (Kaufhäufigkeit).<br><br>Für die AlpenBar: <em>Segment 1</em> – Sportler, 20–35 Jahre, kaufen für unterwegs. <em>Segment 2</em> – Gesundheitsbewusste Familien, 30–45 Jahre, kaufen für Kinder und sich selbst.`
    ],
  preisgestaltung: [
      `<strong>Deckungsbeitrag (DB)</strong> = Verkaufspreis − variable Kosten pro Stück.<br>Er zeigt, wie viel jedes verkaufte Produkt zur Deckung der Fixkosten beiträgt. Erst wenn alle Fixkosten gedeckt sind, entsteht Gewinn.<br><br>AlpenBar: DB = € 2,49 − € 0,85 = <strong>€ 1,64 pro Stück</strong>`,
      `<strong>Cost-Plus-Pricing</strong> (Kostenaufschlagsmethode): Preis = Gesamtkosten + Gewinnaufschlag.<br>Gesamtkosten/Stück: € 0,85 (variabel) + € 0,80 (fix) = € 1,65<br>+ 40 % Aufschlag: € 1,65 × 1,40 = <strong>€ 2,31</strong>`,
      `<strong>Niedrigpreis:</strong> z.B. Hofer/Aldi-Eigenmarken, Billa Clever-Produkte → viele Kunden, geringe Marge.<br><strong>Premiumpreis:</strong> z.B. Ja! Natürlich, Bio Austria-Produkte, Apple, Nespresso → weniger Kunden, aber hohe Marge und starkes Markenimage.`,
      `<strong>Empfehlung: € 2,49 (Premiumpreis)</strong><br>Begründung: AlpenFresh positioniert sich als regionales Bio-Premiumprodukt. Ein zu niedriger Preis würde das Markenimage beschädigen. € 2,49 liegt im Mittelfeld der Konkurrenz (€ 2,10–€ 2,80) und signalisiert Qualität. Bei 15.000 Stück/Monat entsteht ein Gewinn von € 12.600/Monat – wirtschaftlich sinnvoll.`
    ],
  personal: [
      `<strong>5-stufiger Prozess bei AlpenFresh (Produktionsleiterin):</strong><ol><li><strong>Anforderungsprofil festlegen:</strong> Fachliche Qualifikationen (Lebensmitteltechnik, Führungserfahrung), persönliche Eigenschaften (Organisationstalent, Durchsetzungsvermögen)</li><li><strong>Personalsuche starten:</strong> Intern (Beförderung?), extern (AMS, karriere.at, Social Media, Fachhochschulen)</li><li><strong>Vorauswahl treffen:</strong> Bewerbungsunterlagen sichten, Shortlist mit den besten Kandidatinnen erstellen</li><li><strong>Auswahlverfahren:</strong> Strukturiertes Vorstellungsgespräch, evtl. Probearbeitstag in der Produktion</li><li><strong>Einstellung:</strong> Dienstvertrag abschließen, Onboarding planen (Einarbeitung, Mentorin, 3-Monats-Zielgespräch)</li></ol>Für kleine Unternehmen besonders wichtig: Schritt 1 (klares Anforderungsprofil spart Zeit) und Schritt 5 (gutes Onboarding senkt die Fluktuation).`,
      `<strong>Maslow – 5 Stufen mit AlpenFresh-Beispielen:</strong><ol><li><strong>Physiologische Bedürfnisse:</strong> Pünktliches Gehalt, Pausenraum mit Mahlzeiten</li><li><strong>Sicherheit:</strong> Fester Arbeitsvertrag, sichere Produktionsumgebung</li><li><strong>Soziale Bedürfnisse:</strong> Teamevents, kollegiales Klima, gemeinsame Mittagessen</li><li><strong>Wertschätzung:</strong> Lob, Anerkennung von Leistung, Mitsprache bei Entscheidungen</li><li><strong>Selbstverwirklichung:</strong> Eigene Projekte leiten, Weiterbildung, mehr Verantwortung übernehmen</li></ol>Wenn Mitarbeiter trotz gutem Gehalt kündigen, fehlt meist Stufe 4 (Wertschätzung) oder Stufe 5 (Entwicklung und Sinn).`,
      `<strong>Herzberg – Zuordnung der Faktoren:</strong><br><table><tr><th>Faktor</th><th>Typ</th><th>Wirkung bei Vorhandensein</th></tr><tr><td>Gehalt</td><td>Hygienefaktor</td><td>Verhindert Unzufriedenheit</td></tr><tr><td>Lob durch die Chefin</td><td>Motivator</td><td>Schafft Zufriedenheit</td></tr><tr><td>Jobsicherheit</td><td>Hygienefaktor</td><td>Verhindert Unzufriedenheit</td></tr><tr><td>Interessante Aufgaben</td><td>Motivator</td><td>Schafft Zufriedenheit</td></tr><tr><td>Angenehme Teamkultur</td><td>Hygienefaktor</td><td>Verhindert Unzufriedenheit</td></tr><tr><td>Karrierechancen</td><td>Motivator</td><td>Schafft Zufriedenheit</td></tr></table><br>Wichtig: Hygienefaktoren schaffen keine Zufriedenheit, aber ihr Fehlen macht unzufrieden. Nur Motivatoren führen zu echter Arbeitsmotivation.`,
      `<strong>Employer Branding</strong> = alle Maßnahmen, mit denen ein Unternehmen als attraktiver Arbeitgeber wahrgenommen wird.<br><br><strong>3 Maßnahmen für AlpenFresh:</strong><ol><li><strong>Authentische Social-Media-Präsenz:</strong> Instagram-Einblicke in den Produktionsalltag und das Team zeigen die Unternehmenskultur (Bio, Nachhaltigkeit, Teamgeist) und sprechen werteorientierte Bewerber an.</li><li><strong>Mitarbeiterstimmen auf der Website:</strong> Echte Zitate und Fotos der Mitarbeiter wirken glaubwürdiger als Marketingtexte und stärken das Vertrauen potenzieller Bewerber.</li><li><strong>Attraktives Benefitpaket:</strong> Flexible Arbeitszeiten, Weiterbildungsbudget, Mitarbeiterrabatt auf AlpenFresh-Produkte – schafft konkreten Mehrwert über das Gehalt hinaus.</li></ol>`
    ],
  recht: [
      `<strong>GmbH</strong> (Gesellschaft mit beschränkter Haftung): Mindestkapital € 10.000, Haftung beschränkt auf Stammkapital → Privatvermögen geschützt. Vorteil: Haftungsschutz. Nachteil: Gründungskosten (Notar), laufende Buchführungspflicht.<br><strong>Einzelunternehmen (e.U.):</strong> Kein Mindestkapital, einfache Gründung, aber volle Haftung mit Privatvermögen. → Für kleine Gründer mit geringem Risiko geeignet.`,
      `<strong>4 wichtige Bestandteile eines Kaufvertrags:</strong><ol><li>Ware/Leistung (genaue Bezeichnung)</li><li>Menge und Qualität</li><li>Preis (netto/brutto, inkl./exkl. MwSt.)</li><li>Liefertermin und Lieferort</li><li>Zahlungsbedingungen (z.B. 30 Tage netto)</li></ol>`,
      `Bei mangelhafter oder verspäteter Lieferung hat der Käufer folgende Rechte: (1) <strong>Verbesserung</strong> (Reparatur oder Austausch), (2) <strong>Preisminderung</strong>, (3) <strong>Wandlung</strong> (Rücktritt vom Vertrag). Bei Verbrauchern gilt eine gesetzliche Gewährleistungsfrist von <strong>2 Jahren</strong> (§ 924 ABGB). Das Rücktrittsrecht bei Fernabsatz beträgt 14 Tage (KSchG).`,
      `Schriftliche Verträge sind wichtig, weil: (1) alle vereinbarten Konditionen dokumentiert sind, (2) bei Streitigkeiten Beweise vorhanden sind, (3) Missverständnisse vermieden werden, (4) manche Vertragsarten die Schriftform gesetzlich verlangen (z.B. Leasingverträge, Arbeitsverträge für bestimmte Klauseln). Mündliche Verträge sind zwar grundsätzlich gültig, aber schwer beweisbar.`
    ],
  expansion: [
      `<strong>4 konkrete Risiken einer internationalen Expansion:</strong><ul><li><strong>Wirtschaftlich:</strong> Hohe Anlaufkosten für Marktaufbau, unsichere Absatzmenge, Preisdruck durch lokale Konkurrenz</li><li><strong>Kulturell:</strong> Andere Essgewohnheiten und Präferenzen, andere Kommunikationsstile</li><li><strong>Rechtlich:</strong> Andere Lebensmittelkennzeichnungspflichten, andere MwSt.-Sätze, andere Vertragsrechte</li><li><strong>Finanziell:</strong> Wechselkursrisiko (Schweiz), höhere Logistikkosten, Zahlungsausfallrisiko bei ausländischen Kunden</li></ul>`,
      `<strong>Südtirol vs. Schweiz – kultureller Vergleich:</strong><ul><li><strong>Sprache:</strong> Südtirol deutschsprachig → keine Übersetzungskosten. Schweiz: 4 Landessprachen, aber Deutschschweiz als Hauptmarkt ebenfalls deutschsprachig</li><li><strong>Regionalität:</strong> Südtiroler schätzen Tiroler Produkte als „Nachbarn" → hohe Akzeptanz</li><li><strong>Bio-Affinität:</strong> Beide Regionen haben hohe Bio-Affinität</li><li><strong>Kaufkraft:</strong> Schweiz deutlich höher → höhere Preise möglich, aber auch höhere Konkurrenz</li></ul>`,
      `<strong>Wechselkursrisiko:</strong> Wenn AlpenFresh in CHF fakturiert und der CHF gegenüber dem EUR an Wert verliert, bekommt AlpenFresh weniger Euro für dieselbe Ware.<br><br>Beispiel: CHF 3,20 × 0,95 = € 3,04. Fällt der Kurs auf 0,90: CHF 3,20 × 0,90 = € 2,88 → Verlust von € 0,16/Stück. Das Risiko kann durch <strong>Fakturierung in Euro</strong> auf den Schweizer Kunden übertragen werden.`,
      `<strong>Empfehlung: Südtirol zuerst</strong><br>Begründung: Gleiche Währung (€), deutschsprachig, kulturelle Nähe zu Tirol, EU-Binnenmarkt (kein Zoll), Bio-affine Bevölkerung. AlpenFresh kann den Markteintritt mit geringem Risiko testen, bevor es in die aufwändigere Schweiz-Expansion investiert.`
    ],
};