const LOESUNGEN_HLW3 = {
  marketing: [
      `<strong>Marketing-Mix (4 P's) für die AlpenBar:</strong><ul><li><strong>Produkt:</strong> Bio-Müsliriegel mit Tiroler Heumilchschokolade, regional und nachhaltig</li><li><strong>Preis:</strong> € 2,49 – Premiumpreis, passend zum Bio-Image</li><li><strong>Distribution (Place):</strong> Supermärkte (SPAR, REWE), Bio-Läden, Onlineshop</li><li><strong>Kommunikation (Promotion):</strong> Social Media, Verkostungen, regionale Werbung</li></ul>`,
      `<strong>Primärforschung:</strong> Neue Daten werden selbst erhoben (z.B. Umfrage, Interview, Beobachtung). Teurer, aber genau auf die Fragestellung zugeschnitten.<br>Beispiel AlpenFresh: Online-Umfrage zur Zahlungsbereitschaft.<br><br><strong>Sekundärforschung:</strong> Bereits vorhandene Daten werden genutzt (z.B. Statistiken, Studien). Günstiger, aber nicht immer aktuell.<br>Beispiel AlpenFresh: Statistik Austria-Daten zum Bio-Konsum in Österreich.`,
      `<strong>Geeignete Social-Media-Kanäle für 25–45 Jahre:</strong><ul><li><strong>Instagram:</strong> Visuelle Plattform, ideal für Food-Produkte, hohe Nutzung in der Zielgruppe</li><li><strong>Facebook:</strong> Erreicht gut die Gruppe 35–45, geeignet für Community und Events</li><li><strong>TikTok:</strong> Wächst stark, eher 20–35 Jahre, aber gutes virales Potenzial</li></ul>LinkedIn und Twitter weniger geeignet – zu business-orientiert für ein Konsumprodukt.`,
      `<strong>Zielgruppensegmentierung</strong> = Aufteilung des Gesamtmarktes in Gruppen mit ähnlichen Merkmalen. Kriterien: demografisch (Alter, Geschlecht), geografisch (Region), psychografisch (Werte, Lebensstil), verhaltensorientiert (Kaufhäufigkeit).<br><br>Für die AlpenBar: <em>Segment 1</em> – Sportler, 20–35 Jahre, kaufen für unterwegs. <em>Segment 2</em> – Gesundheitsbewusste Familien, 30–45 Jahre, kaufen für Kinder und sich selbst.`
    ],
  preisgestaltung: [
      `<strong>Deckungsbeitrag (DB)</strong> = Verkaufspreis − variable Kosten pro Stück.<br>Er zeigt, wie viel jedes verkaufte Produkt zur Deckung der Fixkosten beiträgt. Erst wenn alle Fixkosten gedeckt sind, entsteht Gewinn.<br><br>AlpenBar: DB = € 2,49 − € 0,85 = <strong>€ 1,64 pro Stück</strong>`,
      `<strong>Cost-Plus-Pricing</strong> (Kostenaufschlagsmethode): Preis = Gesamtkosten + Gewinnaufschlag.<br>Gesamtkosten/Stück: € 0,85 (variabel) + € 0,80 (fix) = € 1,65<br>+ 40 % Aufschlag: € 1,65 × 1,40 = <strong>€ 2,31</strong>`,
      `<strong>Niedrigpreis:</strong> z.B. Hofer/Aldi-Eigenmarken, Billa Clever-Produkte → viele Kunden, geringe Marge.<br><strong>Premiumpreis:</strong> z.B. Ja! Natürlich, Bio Austria-Produkte, Apple, Nespresso → weniger Kunden, aber hohe Marge und starkes Markenimage.`,
      `<strong>Empfehlung: € 2,49 (Premiumpreis)</strong><br>Begründung: AlpenFresh positioniert sich als regionales Bio-Premiumprodukt. Ein zu niedriger Preis würde das Markenimage beschädigen. € 2,49 liegt im Mittelfeld der Konkurrenz (€ 2,10–€ 2,80) und signalisiert Qualität. Bei 15.000 Stück/Monat entsteht ein Gewinn von € 12.600/Monat – wirtschaftlich sinnvoll.`
    ],
  personal: [
      `<strong>5-stufiger Prozess bei AlpenFresh (Produktionsleiterin):</strong><ol><li><strong>Anforderungsprofil festlegen:</strong> Fachliche Qualifikationen (Lebensmitteltechnik, Führungserfahrung), persönliche Eigenschaften (Organisationstalent, Durchsetzungsvermögen)</li><li><strong>Personalsuche starten:</strong> Intern (Beförderung?), extern (AMS, karriere.at, Social Media, Fachhochschulen)</li><li><strong>Vorauswahl treffen:</strong> Bewerbungsunterlagen sichten, Shortlist mit den besten Kandidatinnen erstellen</li><li><strong>Auswahlverfahren:</strong> Strukturiertes Vorstellungsgespräch, evtl. Probearbeitstag in der Produktion</li><li><strong>Einstellung:</strong> Dienstvertrag abschließen, Onboarding planen (Einarbeitung, Mentorin, 3-Monats-Zielgespräch)</li></ol>Für kleine Unternehmen besonders wichtig: Schritt 1 (klares Anforderungsprofil spart Zeit) und Schritt 5 (gutes Onboarding senkt die Fluktuation).`,
      `<strong>Maslow – 5 Stufen mit AlpenFresh-Beispielen:</strong><ol><li><strong>Physiologische Bedürfnisse:</strong> Pünktliches Gehalt, Pausenraum mit Mahlzeiten</li><li><strong>Sicherheit:</strong> Fester Arbeitsvertrag, sichere Produktionsumgebung</li><li><strong>Soziale Bedürfnisse:</strong> Teamevents, kollegiales Klima, gemeinsame Mittagessen</li><li><strong>Wertschätzung:</strong> Lob, Anerkennung von Leistung, Mitsprache bei Entscheidungen</li><li><strong>Selbstverwirklichung:</strong> Eigene Projekte leiten, Weiterbildung, mehr Verantwortung übernehmen</li></ol>Wenn Mitarbeiter trotz gutem Gehalt kündigen, fehlt meist Stufe 4 (Wertschätzung) oder Stufe 5 (Entwicklung und Sinn).`,
      `<strong>Herzberg – Zuordnung der Faktoren:</strong><br><table><tr><th>Faktor</th><th>Typ</th><th>Wirkung bei Vorhandensein</th></tr><tr><td>Gehalt</td><td>Hygienefaktor</td><td>Verhindert Unzufriedenheit</td></tr><tr><td>Lob durch die Chefin</td><td>Motivator</td><td>Schafft Zufriedenheit</td></tr><tr><td>Jobsicherheit</td><td>Hygienefaktor</td><td>Verhindert Unzufriedenheit</td></tr><tr><td>Interessante Aufgaben</td><td>Motivator</td><td>Schafft Zufriedenheit</td></tr><tr><td>Angenehme Teamkultur</td><td>Hygienefaktor</td><td>Verhindert Unzufriedenheit</td></tr><tr><td>Karrierechancen</td><td>Motivator</td><td>Schafft Zufriedenheit</td></tr></table><br>Wichtig: Hygienefaktoren schaffen keine Zufriedenheit, aber ihr Fehlen macht unzufrieden. Nur Motivatoren führen zu echter Arbeitsmotivation.`,
      `<strong>Employer Branding</strong> = alle Maßnahmen, mit denen ein Unternehmen als attraktiver Arbeitgeber wahrgenommen wird.<br><br><strong>3 Maßnahmen für AlpenFresh:</strong><ol><li><strong>Authentische Social-Media-Präsenz:</strong> Instagram-Einblicke in den Produktionsalltag und das Team zeigen die Unternehmenskultur (Bio, Nachhaltigkeit, Teamgeist) und sprechen werteorientierte Bewerber an.</li><li><strong>Mitarbeiterstimmen auf der Website:</strong> Echte Zitate und Fotos der Mitarbeiter wirken glaubwürdiger als Marketingtexte und stärken das Vertrauen potenzieller Bewerber.</li><li><strong>Attraktives Benefitpaket:</strong> Flexible Arbeitszeiten, Weiterbildungsbudget, Mitarbeiterrabatt auf AlpenFresh-Produkte – schafft konkreten Mehrwert über das Gehalt hinaus.</li></ol>`
    ],
  fuehrung: [
      `<strong>Managementebenen mit österreichischen Beispielen:</strong><ul><li><strong>Topmanagement</strong> (normative + strategische Entscheidungen): Birgit Noggler-Gürtler (CEO Manner) → entscheidet über Unternehmensphilosophie und Expansionsstrategie. Bei AlpenFresh: Geschäftsführerin Nina Berger.</li><li><strong>Middle Management</strong> (strategische + operative Entscheidungen): Marketingdirektor bei Spar → setzt Kampagnenstrategie um. Bei AlpenFresh: Produktionsleiterin.</li><li><strong>Lower Management</strong> (operative Aufgaben): Schichtleiter in der Produktion → führt Tagesgeschäft durch. Bei AlpenFresh: Vorarbeiter in der Abfüllanlage.</li></ul>`,
      `<strong>SWOT-Analyse</strong> = Methode zur systematischen Analyse eines Unternehmens. Intern (Stärken/Schwächen) = was das Unternehmen selbst beeinflussen kann. Extern (Chancen/Risiken) = Umfeldfaktoren.<br><br><table><tr><th>Stärken</th><th>Schwächen</th></tr><tr><td>• Bio-zertifiziert & regional<br>• Direktvertrieb online</td><td>• Geringe Kapazität<br>• Wenig Bekanntheit außerhalb Tirols</td></tr><tr><th>Chancen</th><th>Risiken</th></tr><tr><td>• Wachsende Bio-Nachfrage<br>• Expansion nach Deutschland</td><td>• Neue Konkurrenten<br>• Steigende Rohstoffpreise</td></tr></table>`,
      `<strong>Fünf-Kräfte-Modell von Porter</strong> analysiert das Wettbewerbsumfeld eines Unternehmens anhand von 5 Kräften:<br><br><strong>3 Beispiele für AlpenFresh:</strong><ol><li><strong>Rivalität unter Wettbewerbern:</strong> Viele Bio-Start-ups (mymuesli, Local Heroes) drängen auf den Markt → AlpenFresh muss durch Regionalität und Qualität punkten.</li><li><strong>Verhandlungsmacht der Lieferanten:</strong> Wenige Bio-Bauern in Tirol → hohe Abhängigkeit → Lösung: langfristige Verträge abschließen.</li><li><strong>Bedrohung durch Substitutionsprodukte:</strong> Konventionelle Produkte sind günstiger → AlpenFresh muss den Mehrwert (Gesundheit, Umwelt) klar kommunizieren.</li></ol>`,
      `<strong>Führungsstile im Vergleich:</strong><br><table><tr><th>Stil</th><th>Merkmal</th><th>Vorteil</th><th>Nachteil</th></tr><tr><td>Autoritär</td><td>Chef entscheidet allein</td><td>Schnelle Entscheidungen</td><td>Wenig Motivation, kein Engagement</td></tr><tr><td>Kooperativ</td><td>Mitarbeiter werden einbezogen</td><td>Hohe Motivation, bessere Ideen</td><td>Zeitaufwändiger</td></tr><tr><td>Laissez-faire</td><td>Mitarbeiter entscheiden selbst</td><td>Maximale Freiheit & Kreativität</td><td>Risiko von Chaos, keine klare Richtung</td></tr></table><br>Für AlpenFresh als wachsendes Start-up empfiehlt sich der <strong>kooperative Führungsstil</strong>: Mitarbeiter bringen Ideen ein (z.B. neue Produkte), das fördert Innovation und Bindung – wichtig um Talente zu halten.`
    ],
  investition: [
      `<strong>Eigen- vs. Fremdfinanzierung:</strong><br><strong>Eigenfinanzierung</strong> = Kapital der Eigentümer (keine Rückzahlungspflicht). Beispiele: Einlage der Gesellschafter, einbehaltene Gewinne (Selbstfinanzierung).<br><strong>Fremdfinanzierung</strong> = Kapital von Dritten (Rückzahlung + Zinsen). Beispiele: Bankkredit, Anleihe, Lieferantenkredit.<br><br><strong>Innen- vs. Außenfinanzierung:</strong><br><strong>Innenfinanzierung</strong> = Mittel entstehen im Betrieb selbst. Beispiele: Cashflow aus Gewinnen, Verkauf nicht benötigter Anlagen.<br><strong>Außenfinanzierung</strong> = Kapital wird von außen zugeführt. Beispiele: Bankkredit, Kapitalerhöhung durch neue Gesellschafter.`,
      `<strong>Vier Crowdfunding-Modelle:</strong><ol><li><strong>Donation-based:</strong> Spende ohne Gegenleistung (z.B. Klimaschutzprojekt). Vorteil: keine Rückzahlung. Nachteil: meist nur kleine Beträge.</li><li><strong>Reward-based:</strong> Unterstützer erhalten ein Produkt (z.B. Kickstarter-Kampagne für neues Gadget). Vorteil: Kundenbindung + Marketing. Nachteil: Lieferpflicht.</li><li><strong>Lending-based:</strong> Viele geben kleinen Kredit (z.B. Conda, Fundera). Vorteil: günstig. Nachteil: Rückzahlungspflicht.</li><li><strong>Equity-based:</strong> Investoren erhalten Unternehmensanteile (z.B. Seedmatch). Vorteil: viel Kapital möglich. Nachteil: Mitspracherechte der Investoren.</li></ol>`,
      `Drei Gründe für eine Investitionsrechnung vor großen Investitionen:<ol><li><strong>Amortisationsprüfung:</strong> Wann hat sich die Investition bezahlt gemacht? Wenn die Amortisationsdauer länger als die Nutzungsdauer ist → unvorteilhaft.</li><li><strong>Alternativenvergleich:</strong> Welche von mehreren Optionen ist die günstigste? (Kostenvergleichsrechnung: Maschine A vs. B)</li><li><strong>Fremdkapitalgeber verlangen es:</strong> Banken finanzieren nur, wenn eine fundierte Wirtschaftlichkeitsrechnung vorliegt – ohne Rechnung kein Kredit.</li></ol>`,
      `<strong>Empfehlung: Bankkredit</strong><br>Begründung: Eigenkapital (€ 190.000) wäre für eine Maschine von € 240.000 nicht ausreichend ohne die Liquidität zu gefährden. Leasing ist über 8 Jahre teurer. Mit einem Kredit bei 4 % Zinsen bleibt die Maschine Eigentum von AlpenFresh und kann steuerlich abgeschrieben werden. Die laufenden Kosteneinsparungen durch die neue Maschine decken die Kreditrate gut ab.<br><br>Tipp: Vor dem Kredit staatliche Förderungen prüfen (AWS Gründerkredit, Wirtschaftsförderung Tirol, ERP-Kredit).`
    ],
  expansion: [
      `<strong>4 konkrete Risiken einer internationalen Expansion:</strong><ul><li><strong>Wirtschaftlich:</strong> Hohe Anlaufkosten für Marktaufbau, unsichere Absatzmenge, Preisdruck durch lokale Konkurrenz</li><li><strong>Kulturell:</strong> Andere Essgewohnheiten und Präferenzen, andere Kommunikationsstile</li><li><strong>Rechtlich:</strong> Andere Lebensmittelkennzeichnungspflichten, andere MwSt.-Sätze, andere Vertragsrechte</li><li><strong>Finanziell:</strong> Wechselkursrisiko (Schweiz), höhere Logistikkosten, Zahlungsausfallrisiko bei ausländischen Kunden</li></ul>`,
      `<strong>Südtirol vs. Schweiz – kultureller Vergleich:</strong><ul><li><strong>Sprache:</strong> Südtirol deutschsprachig → keine Übersetzungskosten. Schweiz: 4 Landessprachen, aber Deutschschweiz als Hauptmarkt ebenfalls deutschsprachig</li><li><strong>Regionalität:</strong> Südtiroler schätzen Tiroler Produkte als „Nachbarn" → hohe Akzeptanz</li><li><strong>Bio-Affinität:</strong> Beide Regionen haben hohe Bio-Affinität</li><li><strong>Kaufkraft:</strong> Schweiz deutlich höher → höhere Preise möglich, aber auch höhere Konkurrenz</li></ul>`,
      `<strong>Wechselkursrisiko:</strong> Wenn AlpenFresh in CHF fakturiert und der CHF gegenüber dem EUR an Wert verliert, bekommt AlpenFresh weniger Euro für dieselbe Ware.<br><br>Beispiel: CHF 3,20 × 0,95 = € 3,04. Fällt der Kurs auf 0,90: CHF 3,20 × 0,90 = € 2,88 → Verlust von € 0,16/Stück. Das Risiko kann durch <strong>Fakturierung in Euro</strong> auf den Schweizer Kunden übertragen werden.`,
      `<strong>Empfehlung: Südtirol zuerst</strong><br>Begründung: Gleiche Währung (€), deutschsprachig, kulturelle Nähe zu Tirol, EU-Binnenmarkt (kein Zoll), Bio-affine Bevölkerung. AlpenFresh kann den Markteintritt mit geringem Risiko testen, bevor es in die aufwändigere Schweiz-Expansion investiert.`
    ],
  tourismus: [
      `<strong>Tourismusarten der drei Gästesegmente:</strong><table><tr><th>Gästesegment</th><th>Tourismusart</th><th>Unterart</th></tr><tr><td>Kulturgäste (Musikfestival)</td><td>Kulturtourismus</td><td>Eventtourismus</td></tr><tr><td>Wanderurlauber</td><td>Sporttourismus</td><td>Aktiver Sporttourismus</td></tr><tr><td>Wellness-Gäste</td><td>Erholungstourismus</td><td>Wellnesstourismus</td></tr></table><br><strong>Tourismus vs. Freizeitwirtschaft:</strong><br>Tourismus: Eine Familie aus Deutschland übernachtet 5 Nächte im Bergblick Hotel → Reise mit Übernachtung außerhalb des Wohnorts.<br>Freizeitwirtschaft: Eine Person aus Seefeld geht am Nachmittag zur Wellness-Oase im Ort und kehrt abends heim → Freizeitaktivität in der gewohnten Umgebung, keine Übernachtung.`,
      `<strong>Dienstleistungsbilanz:</strong> Die Dienstleistungsbilanz erfasst alle Einnahmen und Ausgaben eines Landes im grenzüberschreitenden Austausch von Dienstleistungen. Wenn ausländische Gäste in Österreich Geld ausgeben (Hotel, Restaurant, Souvenirs), fließt Geld ins Land → positiver Beitrag zur Dienstleistungsbilanz.<br><br><strong>Volkswirtschaftliche Auswirkungen:</strong><ul><li>✅ <strong>Positiv – Deviseneinnahmen:</strong> Deutsche und italienische Gäste geben im Bergblick Hotel pro Nacht ca. € 180–250 aus → Mittelzufluss für Österreich</li><li>✅ <strong>Positiv – Arbeitsplätze:</strong> Das Hotel beschäftigt 22 Mitarbeiter (inkl. saisonal), fördert indirekt regionale Betriebe (Tischler, Wäscherei, Lebensmittellieferanten)</li><li>❌ <strong>Negativ – Abhängigkeit und Saisonalität:</strong> In der Nebensaison sinken Einnahmen stark; bei Krisen (Pandemie, Extremwetter) bricht der Tourismus ein</li></ul>`,
      `<strong>Overtourism</strong> = Überlastung eines Reiseziels durch zu viele Touristen, wodurch Umwelt und Lebensqualität der Einheimischen leiden.<br><br><strong>Maßnahmen für das Bergblick Hotel:</strong><table><tr><th>Dimension</th><th>Maßnahme</th><th>Begründung</th></tr><tr><td>🌿 Ökologisch</td><td>Gäste für Anreise per Bahn belohnen (10 % Rabatt auf Aufenthalt)</td><td>Reduziert PKW-Verkehr und CO₂-Emissionen in Seefeld</td></tr><tr><td>💰 Ökonomisch</td><td>Investition in Online-Direktbuchungssystem</td><td>Spart Provisionen (Booking.com 15–20 %), stärkt Ertragskraft</td></tr><tr><td>🤝 Sozial</td><td>Jobgarantie für Saisonmitarbeiter + Kooperation mit lokalen Vereinen</td><td>Sichert Einkommen, stärkt Akzeptanz in der Dorfgemeinschaft</td></tr></table>`,
      `<strong>Innovation:</strong> Bergblick entwickelt ein „Digital Concierge"-System: Eine Hotel-App mit KI-Chatbot beantwortet 24/7 Fragen, bucht Spa-Anwendungen und empfiehlt personalisierte Wanderrouten basierend auf Wetter und Gästeprofil. → Prozessinnovation (effizienterer Betrieb) + Produktinnovation (neues Serviceangebot).<br><br><strong>Erlebnis & Inszenierung:</strong> Das Hotel inszeniert ein „Alpenglühen-Dinner" auf der Panoramaterrasse: geführte Sonnenuntergangs-Wanderung, Live-Harfe, regionales 4-Gang-Menü. Der Abend ist bewusst „Instagram-tauglich" gestaltet (Fotospot, Hashtag #BergblickMoment) → emotionales Erlebnis, das online geteilt wird und als kostenlose Werbung wirkt.`
    ],
};